kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: clickhouse-server-data-volume
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 100Gi
