apiVersion: v1
kind: Service
metadata:
  name: clickhouse-lb
spec:
  type: LoadBalancer
  selector:
    app: clickhouse-server
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123
      name: port8123
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: port9000
